version: '3.1'
services:
  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3308:3306
    volumes:
      - /home/mariadb/conf:/etc/mysql/conf.d
      - /home/mariadb/data:/var/lib/mysql
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080